[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/uix-proxy/*"
  to = "https://qdmmjjxxztnqupqshiwx.functions.supabase.co/uix-proxy/:splat"
  status = 200
  force = true
